# Generated by Django 5.1 on 2026-01-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_bill_cash_received_bill_change_returned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_pdf_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
