# Generated by Django 4.1.2 on 2022-10-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('mobile', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=40)),
                ('pwd', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=15)),
                ('state', models.CharField(max_length=15)),
                ('zip', models.CharField(max_length=6)),
            ],
        ),
    ]
