# Generated by Django 4.1.2 on 2022-10-29 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='pwd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='login',
            old_name='mobile',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='login',
            name='city',
        ),
        migrations.RemoveField(
            model_name='login',
            name='state',
        ),
        migrations.RemoveField(
            model_name='login',
            name='zip',
        ),
    ]
