# Generated by Django 5.1 on 2026-01-04 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_item_price_itemsize'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='station',
            field=models.CharField(choices=[('KITCHEN', 'Kitchen'), ('BARISTA', 'Barista')], default='KITCHEN', help_text='Preparation station for this item', max_length=20),
        ),
    ]
