# Generated by Django 4.1.2 on 2022-10-29 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_name_login_username'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='contectEnquery',
        ),
    ]
