# Generated by Django 4.1.2 on 2022-10-29 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_login_contectenquery'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contectenquery',
            name='email',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='contectenquery',
            name='password',
            field=models.CharField(max_length=122),
        ),
        migrations.AlterField(
            model_name='contectenquery',
            name='phone',
            field=models.CharField(max_length=122),
        ),
    ]
