# Generated by Django 4.1.2 on 2022-10-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_contectenquery_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='authentic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=112)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
