# Generated by Django 4.1.2 on 2022-11-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_authentic'),
    ]

    operations = [
        migrations.CreateModel(
            name='book_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=122)),
                ('auther', models.CharField(max_length=30)),
                ('publication', models.CharField(max_length=50)),
                ('no_of_pages', models.CharField(max_length=122)),
                ('published_year', models.CharField(max_length=122)),
                ('condition', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=122)),
            ],
        ),
    ]
