# Generated by Django 4.1.2 on 2022-11-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_book_record_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contectenquery',
            name='username',
            field=models.CharField(max_length=122, null=True),
        ),
    ]
