# Generated by Django 4.1.2 on 2022-11-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_contectenquery_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contectenquery',
            old_name='username',
            new_name='user_name',
        ),
    ]
