# Generated by Django 4.1.2 on 2022-11-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_rename_username_contectenquery_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contectenquery',
            name='user_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
