# Generated by Django 4.1.2 on 2022-11-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_contectenquery_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contectenquery',
            name='user_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
