# Generated by Django 4.1.2 on 2023-01-03 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_contectenquery_user_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_record',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
