# Generated by Django 4.1.2 on 2023-01-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_rename_book_record_comment_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_record',
            name='book_file',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
