# Generated by Django 5.1 on 2026-01-04 19:10

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderhistory',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='orderhistory',
            old_name='status',
            new_name='bill_number',
        ),
        migrations.RemoveField(
            model_name='orderhistory',
            name='snapshot',
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='bill_pdf_path',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='cash_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='change_returned',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='customer_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='customer_phone',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='gst',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='items_snapshot',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='payment_mode',
            field=models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI')], default='CASH', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='orderhistory',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='orders.order'),
        ),
    ]
