# Generated by Django 5.1 on 2026-01-04 19:16

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderhistory_options_and_more'),
    ]

    operations = [

        # 🔥 STEP 1: CLEAN BROKEN HISTORY ROWS
        migrations.RunSQL(
            sql="DELETE FROM orders_orderhistory WHERE order_id IS NULL;",
            reverse_sql=migrations.RunSQL.noop,
        ),

        # ---------- META ----------
        migrations.AlterModelOptions(
            name='orderhistory',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Order History',
                'verbose_name_plural': 'Order History',
            },
        ),

        # ---------- SAFE FIELD ALTERATIONS ----------
        migrations.AlterField(
            model_name='orderhistory',
            name='bill_number',
            field=models.CharField(default='UNKNOWN', max_length=30),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='bill_pdf_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='customer_name',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='customer_phone',
            field=models.CharField(default='NA', max_length=15),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='discount',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='gst',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='items_snapshot',
            field=models.JSONField(default=list),
        ),

        # ✅ FK CAN NOW BE SAFELY APPLIED
        migrations.AlterField(
            model_name='orderhistory',
            name='order',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='history',
                to='orders.order',
            ),
        ),

        migrations.AlterField(
            model_name='orderhistory',
            name='payment_mode',
            field=models.CharField(
                choices=[('CASH', 'Cash'), ('UPI', 'UPI')],
                default='CASH',
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='subtotal',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='total_amount',
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal('0.00'),
                max_digits=12,
            ),
        ),
    ]