# Generated by Django 5.1 on 2026-01-04 19:21

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderhistory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderhistory',
            name='cash_received',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='orderhistory',
            name='change_returned',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10, null=True),
        ),
    ]
